# Generated by Django 3.1 on 2021-02-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activation_coe',
            new_name='activation_code',
        ),
    ]
